package main

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"

	"github.com/nick/proctmux/internal/config"
)

// RunConfigInit creates a starter configuration file with comprehensive comments.
// args should contain the original CLI arguments (including the command name).
func RunConfigInit(args []string) error {
	outputPath := "proctmux.yaml"

	if len(args) > 2 {
		return fmt.Errorf("config-init accepts at most one optional path argument")
	}
	if len(args) == 2 {
		if trimmed := args[1]; trimmed != "" {
			outputPath = trimmed
		} else {
			return fmt.Errorf("output path must not be empty")
		}
	}

	if _, err := os.Stat(outputPath); err == nil {
		return fmt.Errorf("refusing to overwrite existing file: %s", outputPath)
	} else if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("unable to stat %s: %w", outputPath, err)
	}

	dir := filepath.Dir(outputPath)
	if dir != "." && dir != "" {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("failed to create directory %s: %w", dir, err)
		}
	}

	content := generateConfigTemplate()

	// Validate that the generated YAML parses correctly before writing to disk.
	var cfg config.ProcTmuxConfig
	if err := yaml.Unmarshal([]byte(content), &cfg); err != nil {
		return fmt.Errorf("generated configuration failed validation: %w", err)
	}

	if err := os.WriteFile(outputPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("failed to write %s: %w", outputPath, err)
	}

	fmt.Printf("Created starter configuration at %s\n", outputPath)
	return nil
}

func generateConfigTemplate() string {
	return `# Proctmux Configuration File
# Generated by 'proctmux config-init'
# Full documentation: https://github.com/nick/proctmux#configuration-reference

# =============================================================================
# PROCESS DEFINITIONS (Required)
# =============================================================================
# Define your processes here. Each process has a unique name and configuration.
procs:
  # Example process demonstrating all available attributes
  "example-process":
    # Shell command to execute (alternative: use 'cmd' for array format)
    shell: "echo 'Hello from proctmux!' && sleep 30"

    # Alternative to 'shell': command as an array (use one or the other)
    # cmd: ["/bin/bash", "-c", "echo 'Hello from proctmux!' && sleep 30"]

    # Working directory for the process (optional, defaults to proctmux cwd)
    cwd: "."

    # Environment variables for this process (optional)
    env:
      # Example environment variable override for the child process
      EXAMPLE_VAR: "example_value"

    # Additional paths to append to PATH (optional)
    # add_path: ["/usr/local/bin", "./node_modules/.bin"]

    # Signal to send when stopping (optional, default: 15/SIGTERM)
    # stop: 15

    # Milliseconds to wait before escalating to SIGKILL (optional, default: 3000)
    # stop_timeout_ms: 3000

    # Command to run after the process is stopped/killed (optional)
    # on_kill: ["echo", "Cleanup complete"]

    # Auto-start when proctmux launches (optional, default: false)
    autostart: false

    # Auto-focus output pane after starting (optional, default: false)
    autofocus: false

    # Short description shown in the UI footer (optional)
    description: "Example process demonstrating all configuration options"

    # Long documentation shown in a popup via the 'd' key (optional)
    docs: |
      This is an example process showing every available configuration option.
      Press 'd' in the UI to view this documentation.

    # Categories for filtering (optional, filter with the 'cat:' prefix)
    categories: ["example", "demo"]

    # Additional tags for metadata (optional, not used by filtering)
    # meta_tags: ["tag1", "tag2"]

# =============================================================================
# GENERAL SETTINGS (Optional)
# =============================================================================
# general:
#   # Name for the background process session (default: "_proctmux")
#   detached_session_name: "_proctmux"
#
#   # Kill existing session if the name already exists (default: true)
#   kill_existing_session: true
#
#   # Automatically create processes from Makefile targets (default: false)
#   procs_from_make_targets: false
#
#   # Automatically create processes from package.json scripts (default: false)
#   procs_from_package_json: false
#   #   The package manager is detected automatically (pnpm, bun, yarn, npm, or deno) based on lock/config files.

# =============================================================================
# LAYOUT SETTINGS (Optional)
# =============================================================================
# layout:
#   # Width of the left process list as a percentage between 1 and 99 (default: 30)
#   processes_list_width: 30
#
#   # Hide the process description panel at the bottom (default: false)
#   hide_process_description_panel: false
#
#   # Sort the process list alphabetically (default: false)
#   sort_process_list_alpha: false
#
#   # Place running processes first when sorting (default: true)
#   sort_process_list_running_first: true
#
#   # Prefix used to activate category filtering (default: "cat:")
#   category_search_prefix: "cat:"
#
#   # Show extra debug info (categories, PID) in the list (default: false)
#   enable_debug_process_info: false

# =============================================================================
# STYLE SETTINGS (Optional)
# =============================================================================
# style:
#   # Character indicating the current selection (default: "▶")
#   pointer_char: "▶"
#
#   # Color of the selected process text (default: "white")
#   selected_process_color: "white"
#
#   # Background color of the selected process (default: "magenta")
#   selected_process_bg_color: "magenta"
#
#   # Color of unselected process text (default: "blue")
#   unselected_process_color: "blue"
#
#   # Color for running process indicators (default: "green")
#   status_running_color: "green"
#
#   # Color for halting process indicators (default: "yellow")
#   status_halting_color: "yellow"
#
#   # Color for stopped process indicators (default: "red")
#   status_stopped_color: "red"
#
#   # Background color of the empty terminal pane (default: "black")
#   placeholder_terminal_bg_color: "black"
#
#   # Foreground color override for the unified terminal pane (optional)
#   # unified_terminal_fg_color: "white"
#
#   # Background color override for the unified terminal pane (default: "black")
#   unified_terminal_bg_color: "black"
#
#   # Color support level: monochrome | ansicolors | 256colors | truecolors (default: "256")
#   color_level: "256"

# =============================================================================
# KEYBINDINGS (Optional - defaults shown)
# =============================================================================
# keybinding:
#   quit: ["q", "ctrl+c"]
#   up: ["k", "up"]
#   down: ["j", "down"]
#   start: ["s", "enter"]
#   stop: ["x"]
#   restart: ["r"]
#   filter: ["/"]
#   submit_filter: ["enter"]
#   toggle_running: ["R"]
#   toggle_help: ["?"]
#   toggle_focus: ["ctrl+w"]
#   focus_client: ["ctrl+left"]
#   focus_server: ["ctrl+right"]
#   docs: ["d"]

# =============================================================================
# SIGNAL SERVER (Optional - for remote control via HTTP)
# =============================================================================
# signal_server:
#   # Enable the HTTP signal server (default: false)
#   enable: false
#
#   # Host to bind the server (default: "localhost")
#   host: "localhost"
#
#   # Port to bind the server (default: 9792)
#   port: 9792

# =============================================================================
# LOGGING (Optional)
# =============================================================================
# Path to write application logs (leave empty to disable logging)
# log_file: "/tmp/proctmux.log"

# Path to write stdout debug logs (optional, useful for debugging process output)
# stdout_debug_log_file: "/tmp/proctmux_stdout.log"

# =============================================================================
# OTHER OPTIONS (Optional)
# =============================================================================
# Shell command prefix used for processes defined with 'shell' (default: your $SHELL)
# shell_cmd: ["/bin/bash", "-c"]

# Enable mouse support in the TUI (optional, experimental)
# enable_mouse: true
`
}
