//! Generated starter configuration text.
//! This module is data-heavy by design: the comments in the YAML template are user-facing documentation, not implementation guidance.

pub fn content() []const u8 {
    return 
    \\# Proctmux Configuration File
    \\# Generated by 'proctmux config-init'
    \\
    \\procs:
    \\  example-process:
    \\    shell: "echo 'Hello from proctmux!' && sleep 30"
    \\    cwd: "."
    \\    env:
    \\      EXAMPLE_VAR: "example_value"
    \\    add_path: ["./node_modules/.bin"]
    \\    stop: 15
    \\    stop_timeout_ms: 3000
    \\    on_kill: ["echo", "Cleanup complete"]
    \\    autostart: false
    \\    autofocus: false
    \\    description: "Example process"
    \\    docs: |
    \\      This is an example process showing the available configuration options.
    \\      Press 'd' in the UI to view this documentation.
    \\    categories: ["example", "demo"]
    \\    meta_tags: ["tag1", "tag2"]
    \\    terminal_rows: 24
    \\    terminal_cols: 80
    \\
    \\general:
    \\  procs_from_make_targets: false
    \\  procs_from_package_json: false
    \\
    \\layout:
    \\  processes_list_width: 30
    \\  hide_process_description_panel: false
    \\  hide_process_list_when_unfocused: false
    \\  sort_process_list_alpha: false
    \\  sort_process_list_running_first: false
    \\  category_search_prefix: "cat:"
    \\  enable_debug_process_info: false
    \\
    \\style:
    \\  pointer_char: "▶"
    \\  selected_process_color: "white"
    \\  selected_process_bg_color: "magenta"
    \\  unselected_process_color: "blue"
    \\  status_running_color: "green"
    \\  status_halting_color: "yellow"
    \\  status_stopped_color: "red"
    \\
    \\keybinding:
    \\  quit: ["q", "ctrl+c"]
    \\  up: ["k", "up"]
    \\  down: ["j", "down"]
    \\  start: ["s", "enter"]
    \\  stop: ["x"]
    \\  restart: ["r"]
    \\  filter: ["/"]
    \\  submit_filter: ["enter"]
    \\  toggle_running: ["R"]
    \\  toggle_help: ["?"]
    \\  toggle_focus: ["ctrl+w"]
    \\  focus_client: ["ctrl+left"]
    \\  focus_server: ["ctrl+right"]
    \\  docs: ["d"]
    \\
    \\shell_cmd: ["sh", "-c"]
    \\log_file: ""
    \\stdout_debug_log_file: ""
    \\
    ;
}
